assets:
  compress:
      css: true
      js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md

ga_analytics: UA-96203809-1

gems:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll/imgix

name: Trevor Carr
description: Trevor Carr is a multidiciplinary designer and front-end developer based
  in Baltimore, MD.
timezone: UTC

permalink: pretty

url: # Add your site url

collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: page
    permalink: "/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page

links:
- url: "/colophon"
  title: colophon
  out: false
- url: "/resume"
  title: résumé
  out: false
- url: mailto:info@trevorcarr.info
  title: 'email: info@trevorcarr.info'
  out: true
- url: https://twitter.com/trevorsee
  title: 'twitter: trevorsee'
  out: true
- url: https://www.instagram.com/_tcarr/
  title: 'instagram: _tcarr'
  out: true
- url: https://github.com/trevorsee
  title: 'github: trevorsee'
  out: true

sizes: 100vw
srcset:
- 500
- 750
- 1000
- 1250
- 1500
- 1750
- 2000
- 2250
- 2500
- 2750
- 3000
imgix:
  source: default-value.imgix.net
